### ISSUE TITLE
Conflicting Licensing

### ISSUE THREAD

**Issue by cschneid** [haifengl/smile#11]
The LICENSE file in the project root is APACHE, but the license notice on at least some files is "All Rights Reserved" (for example: https://github.com/haifengl/smile/blob/master/Smile/src/smile/regression/GradientTreeBoost.java).  Can you please clarify and update licensing text?

Thanks!

**Comment by haifengl** [comment]
The library has been in development for several years. At beginning, it is close source to myself. Now I open source it in Apache license. Need some work to update all source files.

**Comment by cschneid** [comment]
Thank you for open sourcing it! Just want to get it by lawyers who might balk at the license text in the files.  :smile:

**Comment by DiegoCatalano** [comment]
Hello Haifeng,

The library is awesome, the code is nicely writted. Congratz !!

I have a question about the license too. I'm development a [framework](https://github.com/DiegoCatalano/Catalano-Framework) in Java and Android in LGPL. I would to know if can you permit to port some classes into my project ?

**Comment by haifengl** [comment]
Hi Diego,

Would you like to create a build script or eclipse project of SmileMiner for Android? I already provide eclipse project files and settings for these projects. Since the library uses only java standard library, it should be easy to port them to Android (except SmilePlot, which uses Swing). Then you can use these libraries in your framework easily. I don't feel that it is a good strategy to copy files to another projects. It will be hard to synchronize our efforts. If you need helps, I definitely would like to work with you together. Thanks!

**Comment by haifengl** [comment]
all copyrights header in source files have been updated. Thanks!

**Comment by DiegoCatalano** [comment]
Hi Haifeng,

I would like to port Random Forest for [Accord.NET](https://github.com/accord-net/framework) (C#), I would like to know if is possible you to give me the permission for write in LGPL, or if can you to do a dual license (apache 2, lgpl) ?

Thanks !!!
