### ISSUE TITLE
Reading Spark models

### ISSUE THREAD

**Issue by kazjote** [haifengl/smile#120]
Is Smile community interested in loading Spark models? https://databricks.com/blog/2016/05/31/apache-spark-2-0-preview-machine-learning-model-persistence.html

Our use case:
We are currently creating our Random Forest models in Spark but want to load them in some ML library to generate predictions in real time. Spark is very inconvenient for this purpose. Using library like Smile looks like perfect tool for real time predictions running on production.

Would you be interested in merging in changes that would allow loading Spark models starting from Random Forest Classifier?

**Comment by haifengl** [comment]
Have you tried training random forest with smile? It is much faster than spark.

**Comment by kazjote** [comment]
Not really.

It is very convenient that we can load our data from multiple sources, join them, transform, prepare training sets and train model using one tool (Spark currently).

If we would switch model generation to Smile, we would have to persist training data outside of spark and run separate training process on separate machine (with Smile). It is more about convenience than money / time.

**Comment by haifengl** [comment]
Have you ever tried smile?

**Comment by haifengl** [comment]
For this special requirement, we can do it with your company's sponsorship. Thanks!

**Comment by myui** [comment]
@kazjote 

You can persist Smile's RandomForest model on Apache Hivemall.  It runs on both [Spark 1.6/2.0](
https://github.com/myui/hivemall/blob/master/spark/spark-2.0/tutorials/randomforest.md
) and [Hive](http://hivemall.incubator.apache.org/userguide/multiclass/iris_randomforest.html).

Feel free to port our model serialization/deserialization scheme (particulary [opCodegen](https://github.com/myui/hivemall/blob/master/core/src/main/java/hivemall/smile/classification/DecisionTree.java#L301) and it's [Evaluator](https://github.com/myui/hivemall/blob/master/core/src/main/java/hivemall/smile/vm/StackMachine.java) ) to Smile while I made some modifications to Smile's implementation due to mismatch in the multi-threading policy, reducing memory usage, serialization, and etc. I think it is easy to share persistent models between Hivemall and Smile for `opCodegen` .

BTW, Smile's DecisionForest is also serializable and thus you can persist it. https://github.com/haifengl/smile/pull/127

**Comment by kazjote** [comment]
Thanks @myui . I will have a look at this.

@haifengl we are still evaluating available options.
