### ISSUE TITLE
Wavelet Transform gives incorrect results

### ISSUE THREAD

**Issue by bernacek** [haifengl/smile#145]
I have noticed that discrete wavelet transform using Haar wavelet does not really match up results given by Mathematica.

For example Haar DWT of sequence {1,2,3,4} gives {3.5355, 3.5355, -0.7071, 2.1213} in your library, while Mathematica gives {5, -2, -0.7071, -0.7071}. I have reproduced your library result in Mathematica by rotating input data to {2,3,4,1} and specifying 1 level of refinement in DiscreteWaveletTransform function.
Differences exist for other wavelets too.
Please correct your algorithm implementation.

**Comment by haifengl** [comment]
Thanks! We did test our implementation against Matlab. I think that the difference is because of the data format. Mathematica assumes that the "Periodic" padding, that is how to extend data beyond boundaries. It is why if you rotate the 1 to back, we get the same results. Also, the input is only 4 elements, we use 1 level here.

**Comment by bernacek** [comment]
Padding is never a problem for Haar wavelets.

Please visit the following page:
https://en.wikipedia.org/wiki/Haar_wavelet#Example
It explains Haar transform of the vector {1,2,3,4} using matrix multiplication and it proofs that the result computed by your library is incorrect.

**Comment by haifengl** [comment]
You are right. Padding is not the issue here. But there are two other things that may cause the difference.

1. In the example of Wiki, H4 matrix is used, which means two stage transformation. As you already noticed, we are doing only level transformation with Haar. It means that we are using H2 matrix in that wiki page.

2. In fact, we are not using the exact same H2 matrix. Most wavelet documents use [1, 1] as coefficients in Haar because it is simple. However, its norm is 2, not 1. In our implementation, we use the coefficient 0.7071067811865475. Similarly, we normalize all other wavelet coefficients to norm 1. You can check these coefficients in smile.wavelet.DaubechiesWavelet, for example. They are different from what you will find in wiki (https://en.wikipedia.org/wiki/Daubechies_wavelet), where they explicitly states that the norm is 2. Some people normalize them to of norm sqrt(2), too. It is mainly a matter of scaling.

I don't have Mathematica. Can you please do me a favor by calculating

DiscreteWaveletTransform([1,2,3,4]) with one level refinement and then scale the result with 0.7071067811865475. I hope this will match our result.

BTW, we have unit tests that all can transform a signal back and forth without errors. And the wavelet shrinkage also works fine. If our DWT is wrong, i cannot image that we can transform the signal back without errors. Thanks!

**Comment by haifengl** [comment]
@bernacek any updates? can we match the results after scaling? Thanks a lot!

**Comment by bernacek** [comment]
No, scaling won't help. The signs in output does not match.
I think there are two problems with your implementations:
1. Haar filter is misaligned with the input signal. Thats why rotating input gives correct result for the first level of DWT.
2. For a 4-element vector should be 2 levels of DWT, not 1; 3 levels for 8-element vector, etc.
Additionally I think that coiflet wavelet filter coefficients are in reverse order.

**Comment by haifengl** [comment]
Most wavelet's coefficients are at least 4. It is why the generic wavelet.transform() method stops at that level. Haar is special with only 2 coefficients. I will add special handling to it in transform().

Can you post the result from Mathematica with one level pass and scaling here? I want check if the sign difference is systematic or not. Thanks!

**Comment by haifengl** [comment]
I checked [JWave] (https://github.com/cscheiblich/JWave/blob/master/src/jwave/transforms/wavelets/coiflet/Coiflet1.java). Our coiflet coefficients match theirs. Which doc/software do you refer about coif let coefficients? Thanks!

**Comment by haifengl** [comment]
Can you confirm that this issue is only with Haar wavelet? After scaling, can other wavelets match Mathematica (let's leave coiflet alone now). This will help me to locate the issues. Thanks!

**Comment by haifengl** [comment]
Some people call it Symmlet, for example http://www.colorado.edu/engineering/CAS/courses.d/ASEN5519.d/kaist.lecture.11.pdf

Not sure which one is "officially" correct spelling :)

For sure, I will make  transform() working until the last pair.

Not sure the coefficients (not matter coiflet and others). I found many different definitions. Don't know how they come up and which one is (absolutely) correct. Coiflet is almost symmetric. Maybe some people don't care if it is reversed?

**Comment by bernacek** [comment]
I'm not so sure either about the spelling, however both Mathematica and Matlab, and most academic papers refer it as "symlet".
I'm sure that most people don't care if the coeffs are reversed, but you might wish to have it in pair with other software.

**Comment by haifengl** [comment]
In the book Numerical Recipes (http://cacs.usc.edu/education/cs653/NRC-c13.10-Wavelets.pdf), the DWT stops at last four samples (not 2). See the wt1 function there. Do I miss something here? Or Haar is special?

**Comment by haifengl** [comment]
In this web page, the order of coiflet coefficients is same as in my code. Does the order really matter in coiflet?

**Comment by haifengl** [comment]
Find the bug with HaarWavelet. It is fixed now and we match the results with Mathematica on [1,2,34] input. Thanks!

**Comment by haifengl** [comment]
Matlab uses this function to calculate how many levels of wavelet transform.

http://www.codeforge.com/read/200483/wmaxlev.m__html

We follow the same rule now.

**Comment by haifengl** [comment]
all changes are pushed to repo. you can try it by clone this project and then run ./smile.sh in the repo. Thanks!
