### ISSUE TITLE
getIndex() method for PCA,PPCA and KPCA.

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#196]
Hi Hai,
There is getIndex() method for iso and lle (manifold learning) algorithms which return the indices of the original dataset. Is there a similar method for Projection(PCA,PPCA and KPCA) algorithms? or there is a one to one mapping between input and output datapoint?

Thanks

**Comment by haifengl** [comment]
PCA/PPCA/KPCA are projection algorithms while IsoMap and LLE are manifold learning. They are different animals.

The reason that IsoMap and LLE provide getIndex is because they work on the largest connected component, which doesn't necessarily cover all the data points. The getIndex method let you know what original data points are used.

A projection algorithm learns the mapping and don't store the the projected data points (actually they don't do this computation at all).

**Comment by aminaaslam** [comment]
Thanks hai for a very prompt reply. Is it safe to say the output points generated by PCA algorithms have one to one mapping with the original datapoints? The reason i am asking is this is because i am plotting the output points and i want to color code them based on their label or class(0 or 1) in the original dataset. If there is one to one mapping between original and output then i can use the same index to get the label of that data row. I hope i am making some sense?

**Comment by haifengl** [comment]
Yes, it is one-to-one mapping. There are examples in demo that do the color coding in visualization with PCA etc.
