### ISSUE TITLE
This library looks great, why does it seem to be a solo project?

### ISSUE THREAD

**Issue by dariomx** [haifengl/smile#273]
Dear Haifeng,

I am just finding about your library, and seems quite attractive to me. I am focusing now on ML methods that are linear-algebra intensive, hence your leverage of nd4j -> blas is exciting.

One thing though, which I may be asked about within my org, is the number of contributors. It seems that you are the only developer ;-?

While is quite impressive that you managed to develop the whole thing yourself, it also brings questions about why it does not have yet a developers community. It seems that nowadays, having an strong community is one of the factors behind the decision to use or not certain 3rd party library. Developers are not the only component of a community, but is usually an strong part of it; and it typically involves more than one person for consolidated projects.

Could you share your thoughts about this please?  I am both curious and very interested ;-? Please find below a set of more concrete questions:

1) Why is this a solo project? Do you prefer working alone or nobody has volunteered yet?

2) It seems you are currently active on this project, but do you have an agenda about how long will you be supporting it? Do you do that as "hobby" or is an integral part of your daily-paid job?

3) Do you have some figures about current usage of this project on Machine Learning/Data Science communities? Some ideas about the future adoption?

Thanks.

**Comment by haifengl** [comment]
The project was developed by myself for several years before open source. When I open sourced it, all major algorithms (> 95%) were there already. Smile has very high quality, proven by the small number of bug reports even with wide usage. We get ten thousands downloads every month. Many leading technology companies use smile based on private communication. Because of these two reasons, the number of additional contributions has been small.

In addition, to contribute to core machine learning library with general purpose language like Java/Scala,  the developers have to be very good at both mathematics and programming. Therefore, the contributor pool is very small by nature.

**Comment by dariomx** [comment]
Thanks a lot by your prompt response Haifeng. While it may not depend entirely on me whether to use it officially within my org, your feedback will certainly use (along with actual experiments that I yet need to conduct).

Saludos.

**Comment by haifengl** [comment]
Feel free to open tickets or ask on gitter if you have any questions on using smile. Thanks.
