### ISSUE TITLE
Add lift to AssociationRule

### ISSUE THREAD

**Issue by scottmutchler** [haifengl/smile#376]
Could you possibly add lift to the AssocationRule class? 

**https://en.wikipedia.org/wiki/Lift_(data_mining)**

Lift is more useful than confidence in most real world applications because confidence doesn't take into account the frequency of the items by themselves.  Thus you get a lot of examples of very frequent items having high confidence with other items (useless).  Lift largely eliminates this.

**Comment by albertmolinermrf** [comment]
I agree that lift (and sometimes also leverage, defined as the difference of supports instead of the quotient) is often a useful measure of a rule.

Among the multiple ways to provide it, probably the following would be the simplest and would not imply any impact at all in performance or resources for those users who are not interested in it. Its downside is that it is not handy when calling `learn(double confidence, PrintStream out)`, only for `learn(double confidence)`.

It requires only adding the following method to `smile.association.ARM`:
```java
    public double getSupport(int[] itemset) {
      return ((double) ttree.getSupport(itemset)) / fim.size();
    }
```

As `AssociationRule` already offers the itemsets of antecedent and consequent, as well as the rule's support, given a rule, the new method could be used to obtain the missing supports and to calculate the resulting lift (or leverage).

Do you think it could be added sometime?

**Comment by haifengl** [comment]
Added in v2. Thanks
