### ISSUE TITLE
[Discussion] License changes from ASLv2 to LGPL in v2.0

### ISSUE THREAD

**Issue by myui** [haifengl/smile#439]
Hi @haifengl 

I can observe you are working on v2.0 of smile and it seems License changes from ASLv2 to LGPL in https://github.com/haifengl/smile/blob/v2/LICENSE

It would be a sensitive topic for Smile users.

Could you share what will introduced/changes in v2.0? The v1.0 branch would not be maintained after the release?

**Comment by haifengl** [comment]
We use LGPL to encourage the users to contribute back to the project. It is a commercial friendly license.

**Comment by myui** [comment]
IMPO, changing ASLv2 to LGPL does not bring user contributions and is not a commercial friendly license. BSD/MIT-like or ASLv2 is preferred by professional users.

Community driven projects brings user contributions. But, of course, it's up to you.

**Comment by johnh84** [comment]
I would agree with @myui. BSD/MIT-like or ASLv2 is preferred by professional users.

**Comment by hageldave** [comment]
Switching to LGPL will force users to publish changes they made to smile. Using smile in closed source (also commercially) is still possible. So in a sense you can say that this "encourages" users to contribute to smile (even though that may be involuntarily).
I think this will not change the number of individual contributors, or the number of contributors that use smile for reasearch. It may bring some contributors from the industry but it may also make industry hesitate to even use smile.

**Comment by rayeaster** [comment]
LGPL allows to reference/use/extend smile as library without open source private/corporate code.

**Comment by lwhite1** [comment]
@haifengl and the other contributors have done amazing things and are free to choose whatever license they want, but I think the idea that LGPL will lead to more contributions may be misguided.

First, requiring people to contribute their enhancements will only produce more contributions if there is a significant community of smile users who've made enhancements and don't contribute them. I think most people want their changes in the core library so they can update easily.

Second, from what I've heard JSAT is also a good Java ML library. It's been around longer than smile, it's GPL'd, and it has about 600 stars compared to smile's 4,500. I once asked its creator to switch to ASL, because I was looking for an ML library to integrate closely with my own project. He declined because he wanted to be sure his users contributed back to his project. Since then, he's had not just fewer users than smile, but fewer contributions. I know GPL and LGPL are different, but they both make companies nervous. 

Finally, my experience with Tablesaw - originally my project, but now maintained by a healthy community - has been that people want to contribute. Tablesaw was really shaky for a long time, but it's a good piece of software now because of all the contributions. At this point I think only the Spark dataframe is in the same ballpark in terms of functionality. (Though of course Spark is miles ahead in users and mindshare. They have a big budget ;). 

Anyway, I hope you'll take this in the spirit intended. Sorry it turned into a long ramble. I've been a fan of smile for a long time. I have some idea how much work has gone into it, and I wish you all the best whatever you decide.

**Comment by haifengl** [comment]
As the debates show that LGPL is business friendly. As far as I know, business is not shy away from using LGPL libraries.

**Comment by gforman44** [comment]
I've been a fan & promoter of SMILE, but with the new LGPL license, I'm not able to use it at my big company.  They freely allow Apache but LGPL v3, GPL and its variants are not usable.  Please go back to Apache.

**Comment by haifengl** [comment]
We are all benefiting from GPL/LGPL software (Linux, GCC, etc). In my opinion, GPL/LGPL is very nice to OSS community. If a business wants to use SMILE but don't feel comfortable with LGPL, they can acquire a commercial license.
