### ISSUE TITLE
Gaussian process regression, calculate error bars.

### ISSUE THREAD

**Issue by herofe** [haifengl/smile#473]
## Question

I tried the GP regression class and found no clear way to get error bars (variance/confidence interval) for a prediction. Is this functionality missing, or is there any other smart way to get them out of the trained regression class using some other methods in this library?

Best Regards,
Herman

**Comment by haifengl** [comment]
We currently don't provide confidence interval as the fitting doesn't estimate the underlying distribution. The nice confidence interval shown in tutorial/textbook is often not from the fitted model, rather than based on the known generative distribution of the toy data. For real data, a costly MCMC is often used to estimate the confidence interval.

**Comment by herofe** [comment]
Hi!

I will be using the variance and the mean in the predictions to decide what arms to pull in a multi armed bandit experiment. I will have under 100 data points in my data, so it will be a "toy" problem sized data set. But anyway it is real valid and expensive data to me…

Do you mean that I cannot use the textbook/tutorial "error-bars" calculus, to estimate where I miss information in the GP predictions for a MAB experiment?

Thanks for your help!

**Comment by haifengl** [comment]
Sorry, I am not familiar with MAB.
