### ISSUE TITLE
Migration notes from Smile 1.X to 2.X

### ISSUE THREAD

**Issue by blacelle** [haifengl/smile#496]
Where can I find some migration notes related to migrating from 1.X to 2.X ?

Typically,:

- where is gone smile.math.Math ?
- where is gone smile.data.NumericAttribute ?
- where is gone Dataset.remove ?
- where is done smile.regression.NeuralNetwork ?
- where is done smile.regression.NeuralNetwork.learn ?
- where is gone ActivationFunction.LOGISTIC_SIGMOID ?

Thanks

**Comment by haifengl** [comment]
2.x is a complete rewrite so that I don't have bandwidth to provide a comprehensive migration guide. In general, please refer the JavaDoc and unit tests how to use the new interface. You can find the answers to your questions quickly there. Here are some quick answers.

- where is gone smile.math.Math ?

MathEx

- where is gone smile.data.NumericAttribute ?

It is gone. Use DataFrame

- where is gone Dataset.remove ?

DataFrame are immutable and you can do filter and many other operations to create a new DataFrame quickly.

where is done smile.regression.NeuralNetwork ?

MLP

**Comment by blacelle** [comment]
Thanks
