### ISSUE TITLE
Crossvalidation Question

### ISSUE THREAD

**Issue by Xyclade** [haifengl/smile#5]
It might be my understanding of cross validation, but when I do do the following:

(Scala code)
val cv  = new CrossValidation(100,1);
val trainingIndexes : Array[Array[Int]] = cv.train
val testingIndexes : Array[Array[Int]] = cv.test

The result is that trainingIndexes is an array with an empty array and the testingIndexes is an array with 1 element with 100 integers. My expectation was both lists containing 50 indexes.

The reason I was using it like this is that I want to do cross validation with 50% of the data (which consists of 100 data points) as training and 50% as testing. Am I doing it wrong, or is there an error in the CrossValidation implementation (since it accepts there parameters but gives no training indexes)

**Comment by haifengl** [comment]
The first parameter of CrossValidation is the number of samples in the data. The second is the number of rounds of cross validation. In your case, it should be 2. BTW, it is better to use a larger number for cross validation (e.g. 5 or 10). Otherwise, the estimated error rate may be very biased.

Besides, Bootstrap may be a better chance for more accurate estimation (with a large number of rounds such as 100). But it takes longer time. Worth to try if your data is not too large.

**Comment by Xyclade** [comment]
Thank you for the quick feedback. The main reason I want to do a 50% training-testing split is because this is exactly how it is done in an example in R, and my goal is to work through that example using Smile instead.  I will experiment a bit more and use Bootstrap too to see how that works. Thanks again!
