### ISSUE TITLE
Error calling DataFrameRegression.predict(DataFrame data) method.

### ISSUE THREAD

**Issue by didekin** [haifengl/smile#537]
Once created a valid RandomForest instance, the `DataFrameRegression.predict(DataFrame data)`method throws an java.lang.IndexOutOfBoundsException.

However, if I bypass that method and I do myself the iteration  calling in each step the `RegressionTree.predict(Tuple x)` method, everything is fine.

Therefore, the problem seems to be in the line `Tuple xt = formula.x(x);` inside the `RandomForest.predict(Tuple x)` method.

..........................
Full source code and data in 
https://gist.github.com/didekin/530095a3a7d5ec16c7eaf14989df1652
..........................
Java version: openjdk 11.0.4 2019-07-16 in MacOS.
Smile 2.3.0

**Comment by haifengl** [comment]
The error indicates that the schema of test data and that of train data mismatches.

**Comment by didekin** [comment]
Thanks for your comment.
In my test:
`@Test
    public void test_RndPredict()
    {
        Promocion promoIn = doPrevState(150);
        RandomForest rndModel = rndForest.get().modelsMap.get(pg1_4).get();
        DataFrame dfNew = of(modelSimulateDao.simulationDataByPg1Result(pg1_4.idPg1, promoIn), RespSimulationDf.class)
                .drop(provincia.name());

        // Check x.schemas of formula and data for prediction.        assertThat(rndModel.formula().xschema().fields()).containsExactly(dfNew.schema().fields());
        assertThat(rndPredict.apply(dfNew, rndModel)).hasSize(dfNew.size()).hasSize(3);
    }`

I included a line to check that the schema of the model and the data of the test are the same:
`assertThat(rndModel.formula().xschema().fields()).containsExactly(dfNew.schema().fields());`

So, I don't think that's the problem.

**Comment by haifengl** [comment]
Try `model.predict(dfNew)`. The model can be applied on the data frame directly. In this way, we can bind the formula to the new schema. If you have to call `predict` on `Tuple`, call `model.formula().bind(t.schema())` first.

**Comment by haifengl** [comment]
Sorry, I mean `model.test(dfNew)`. It is important to call `formula.x()` first. It happens fine in your test bypass this step because the dfNew column order is same as the training data.

There are a lot of considerations in this design to achieve a good balance between performance and flexibility. In short, `Formula` is abstract and independent of a particular `DataFrame`. When you train a model, the formula will bind to the schema of training data frame. For performance reason, we cache this binding as it is costly. When you apply the model to a new data frame (may have extra fields or different column ordering), the formula should be bound to the new schema. This will be done automatically when the saved model is loaded in a new process. And `model.test()` does that too.

 I guess that you train and test the model in the same process. This is usually fine as the test data and training data are usually of the same schema. Interestingly, you create a different schema for test data. That is why `formula.x()` fails. I enhance `model.predict(DataFrame)` to forcefully bind to the new schema. Note that `model.predict(Tuple)` won't do so to avoid the overhead.

**Comment by didekin** [comment]
I thank you for your explanation and your time.
